name: Deploy to production

on:
  push:
    branches: [ "main" ]
  pull_request: # Remove this later using for testing
    branches: [ "main" ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: leoomi/contact-info:latest

      - name: Execute SSH commands in EC2 instace to update container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop app
            docker rm app
            docker pull leoomi/contact-info:latest
            docker run -d --name app -p 80:80 leoomi/contact-info:latest
