name: Deploy to production

on:
  push:
    branches: [ "main" ]
  pull_request: # Remove this later using for testing
    branches: [ "main" ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        users: docker/build-push-action@v4
        with:
          push: true
          tags: leoomi/contact-info:latest
